/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing SocialAccountInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SocialAccountInformationTests
    {
        // TODO uncomment below to declare an instance variable for SocialAccountInformation
        //private SocialAccountInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SocialAccountInformation
            //instance = new SocialAccountInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SocialAccountInformation
        /// </summary>
        [Test]
        public void SocialAccountInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SocialAccountInformation
            //Assert.IsInstanceOfType<SocialAccountInformation> (instance, "variable 'instance' is a SocialAccountInformation");
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Test]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'SocialId'
        /// </summary>
        [Test]
        public void SocialIdTest()
        {
            // TODO unit test for the property 'SocialId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
