/* 
 * Docusign eSignature REST API
 *
 * The Docusign eSignature REST API provides you with a powerful, convenient, and simple Web services API for interacting with Docusign.
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace DocuSign.eSign.Model
{
    /// <summary>
    /// AccountManagementGranular
    /// </summary>
    [DataContract]
    public partial class AccountManagementGranular :  IEquatable<AccountManagementGranular>, IValidatableObject
    {
        public AccountManagementGranular()
        {
            // Empty Constructor
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountManagementGranular" /> class.
        /// </summary>
        /// <param name="AllowManageAccountSecuritySettings">AllowManageAccountSecuritySettings.</param>
        /// <param name="AllowManageAccountSecuritySettingsMetadata">AllowManageAccountSecuritySettingsMetadata.</param>
        /// <param name="AllowManageAccountSettings">AllowManageAccountSettings.</param>
        /// <param name="AllowManageAccountSettingsMetadata">AllowManageAccountSettingsMetadata.</param>
        /// <param name="AllowManageAdmins">AllowManageAdmins.</param>
        /// <param name="AllowManageAdminsMetadata">AllowManageAdminsMetadata.</param>
        /// <param name="AllowManageConnect">AllowManageConnect.</param>
        /// <param name="AllowManageConnectMetadata">AllowManageConnectMetadata.</param>
        /// <param name="AllowManageDocumentRetention">AllowManageDocumentRetention.</param>
        /// <param name="AllowManageDocumentRetentionMetadata">AllowManageDocumentRetentionMetadata.</param>
        /// <param name="AllowManageEnvelopeTransfer">AllowManageEnvelopeTransfer.</param>
        /// <param name="AllowManageEnvelopeTransferMetadata">AllowManageEnvelopeTransferMetadata.</param>
        /// <param name="AllowManageGroupsButNotUsers">AllowManageGroupsButNotUsers.</param>
        /// <param name="AllowManageGroupsButNotUsersMetadata">AllowManageGroupsButNotUsersMetadata.</param>
        /// <param name="AllowManageJointAgreements">AllowManageJointAgreements.</param>
        /// <param name="AllowManageJointAgreementsMetadata">AllowManageJointAgreementsMetadata.</param>
        /// <param name="AllowManageReporting">AllowManageReporting.</param>
        /// <param name="AllowManageReportingMetadata">AllowManageReportingMetadata.</param>
        /// <param name="AllowManageSharing">AllowManageSharing.</param>
        /// <param name="AllowManageSharingMetadata">AllowManageSharingMetadata.</param>
        /// <param name="AllowManageSigningGroups">AllowManageSigningGroups.</param>
        /// <param name="AllowManageSigningGroupsMetadata">AllowManageSigningGroupsMetadata.</param>
        /// <param name="AllowManageStamps">AllowManageStamps.</param>
        /// <param name="AllowManageStampsMetadata">AllowManageStampsMetadata.</param>
        /// <param name="AllowManageUsers">AllowManageUsers.</param>
        /// <param name="AllowManageUsersMetadata">AllowManageUsersMetadata.</param>
        /// <param name="AllowViewUsers">AllowViewUsers.</param>
        public AccountManagementGranular(string AllowManageAccountSecuritySettings = default(string), SettingsMetadata AllowManageAccountSecuritySettingsMetadata = default(SettingsMetadata), string AllowManageAccountSettings = default(string), SettingsMetadata AllowManageAccountSettingsMetadata = default(SettingsMetadata), string AllowManageAdmins = default(string), SettingsMetadata AllowManageAdminsMetadata = default(SettingsMetadata), string AllowManageConnect = default(string), SettingsMetadata AllowManageConnectMetadata = default(SettingsMetadata), string AllowManageDocumentRetention = default(string), SettingsMetadata AllowManageDocumentRetentionMetadata = default(SettingsMetadata), string AllowManageEnvelopeTransfer = default(string), SettingsMetadata AllowManageEnvelopeTransferMetadata = default(SettingsMetadata), string AllowManageGroupsButNotUsers = default(string), SettingsMetadata AllowManageGroupsButNotUsersMetadata = default(SettingsMetadata), string AllowManageJointAgreements = default(string), SettingsMetadata AllowManageJointAgreementsMetadata = default(SettingsMetadata), string AllowManageReporting = default(string), SettingsMetadata AllowManageReportingMetadata = default(SettingsMetadata), string AllowManageSharing = default(string), SettingsMetadata AllowManageSharingMetadata = default(SettingsMetadata), string AllowManageSigningGroups = default(string), SettingsMetadata AllowManageSigningGroupsMetadata = default(SettingsMetadata), string AllowManageStamps = default(string), SettingsMetadata AllowManageStampsMetadata = default(SettingsMetadata), string AllowManageUsers = default(string), SettingsMetadata AllowManageUsersMetadata = default(SettingsMetadata), string AllowViewUsers = default(string))
        {
            this.AllowManageAccountSecuritySettings = AllowManageAccountSecuritySettings;
            this.AllowManageAccountSecuritySettingsMetadata = AllowManageAccountSecuritySettingsMetadata;
            this.AllowManageAccountSettings = AllowManageAccountSettings;
            this.AllowManageAccountSettingsMetadata = AllowManageAccountSettingsMetadata;
            this.AllowManageAdmins = AllowManageAdmins;
            this.AllowManageAdminsMetadata = AllowManageAdminsMetadata;
            this.AllowManageConnect = AllowManageConnect;
            this.AllowManageConnectMetadata = AllowManageConnectMetadata;
            this.AllowManageDocumentRetention = AllowManageDocumentRetention;
            this.AllowManageDocumentRetentionMetadata = AllowManageDocumentRetentionMetadata;
            this.AllowManageEnvelopeTransfer = AllowManageEnvelopeTransfer;
            this.AllowManageEnvelopeTransferMetadata = AllowManageEnvelopeTransferMetadata;
            this.AllowManageGroupsButNotUsers = AllowManageGroupsButNotUsers;
            this.AllowManageGroupsButNotUsersMetadata = AllowManageGroupsButNotUsersMetadata;
            this.AllowManageJointAgreements = AllowManageJointAgreements;
            this.AllowManageJointAgreementsMetadata = AllowManageJointAgreementsMetadata;
            this.AllowManageReporting = AllowManageReporting;
            this.AllowManageReportingMetadata = AllowManageReportingMetadata;
            this.AllowManageSharing = AllowManageSharing;
            this.AllowManageSharingMetadata = AllowManageSharingMetadata;
            this.AllowManageSigningGroups = AllowManageSigningGroups;
            this.AllowManageSigningGroupsMetadata = AllowManageSigningGroupsMetadata;
            this.AllowManageStamps = AllowManageStamps;
            this.AllowManageStampsMetadata = AllowManageStampsMetadata;
            this.AllowManageUsers = AllowManageUsers;
            this.AllowManageUsersMetadata = AllowManageUsersMetadata;
            this.AllowViewUsers = AllowViewUsers;
        }
        
        /// <summary>
        /// Gets or Sets AllowManageAccountSecuritySettings
        /// </summary>
        [DataMember(Name="allowManageAccountSecuritySettings", EmitDefaultValue=false)]
        public string AllowManageAccountSecuritySettings { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageAccountSecuritySettingsMetadata
        /// </summary>
        [DataMember(Name="allowManageAccountSecuritySettingsMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageAccountSecuritySettingsMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageAccountSettings
        /// </summary>
        [DataMember(Name="allowManageAccountSettings", EmitDefaultValue=false)]
        public string AllowManageAccountSettings { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageAccountSettingsMetadata
        /// </summary>
        [DataMember(Name="allowManageAccountSettingsMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageAccountSettingsMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageAdmins
        /// </summary>
        [DataMember(Name="allowManageAdmins", EmitDefaultValue=false)]
        public string AllowManageAdmins { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageAdminsMetadata
        /// </summary>
        [DataMember(Name="allowManageAdminsMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageAdminsMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageConnect
        /// </summary>
        [DataMember(Name="allowManageConnect", EmitDefaultValue=false)]
        public string AllowManageConnect { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageConnectMetadata
        /// </summary>
        [DataMember(Name="allowManageConnectMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageConnectMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageDocumentRetention
        /// </summary>
        [DataMember(Name="allowManageDocumentRetention", EmitDefaultValue=false)]
        public string AllowManageDocumentRetention { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageDocumentRetentionMetadata
        /// </summary>
        [DataMember(Name="allowManageDocumentRetentionMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageDocumentRetentionMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageEnvelopeTransfer
        /// </summary>
        [DataMember(Name="allowManageEnvelopeTransfer", EmitDefaultValue=false)]
        public string AllowManageEnvelopeTransfer { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageEnvelopeTransferMetadata
        /// </summary>
        [DataMember(Name="allowManageEnvelopeTransferMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageEnvelopeTransferMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageGroupsButNotUsers
        /// </summary>
        [DataMember(Name="allowManageGroupsButNotUsers", EmitDefaultValue=false)]
        public string AllowManageGroupsButNotUsers { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageGroupsButNotUsersMetadata
        /// </summary>
        [DataMember(Name="allowManageGroupsButNotUsersMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageGroupsButNotUsersMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageJointAgreements
        /// </summary>
        [DataMember(Name="allowManageJointAgreements", EmitDefaultValue=false)]
        public string AllowManageJointAgreements { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageJointAgreementsMetadata
        /// </summary>
        [DataMember(Name="allowManageJointAgreementsMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageJointAgreementsMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageReporting
        /// </summary>
        [DataMember(Name="allowManageReporting", EmitDefaultValue=false)]
        public string AllowManageReporting { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageReportingMetadata
        /// </summary>
        [DataMember(Name="allowManageReportingMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageReportingMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageSharing
        /// </summary>
        [DataMember(Name="allowManageSharing", EmitDefaultValue=false)]
        public string AllowManageSharing { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageSharingMetadata
        /// </summary>
        [DataMember(Name="allowManageSharingMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageSharingMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageSigningGroups
        /// </summary>
        [DataMember(Name="allowManageSigningGroups", EmitDefaultValue=false)]
        public string AllowManageSigningGroups { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageSigningGroupsMetadata
        /// </summary>
        [DataMember(Name="allowManageSigningGroupsMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageSigningGroupsMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageStamps
        /// </summary>
        [DataMember(Name="allowManageStamps", EmitDefaultValue=false)]
        public string AllowManageStamps { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageStampsMetadata
        /// </summary>
        [DataMember(Name="allowManageStampsMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageStampsMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageUsers
        /// </summary>
        [DataMember(Name="allowManageUsers", EmitDefaultValue=false)]
        public string AllowManageUsers { get; set; }
        /// <summary>
        /// Gets or Sets AllowManageUsersMetadata
        /// </summary>
        [DataMember(Name="allowManageUsersMetadata", EmitDefaultValue=false)]
        public SettingsMetadata AllowManageUsersMetadata { get; set; }
        /// <summary>
        /// Gets or Sets AllowViewUsers
        /// </summary>
        [DataMember(Name="allowViewUsers", EmitDefaultValue=false)]
        public string AllowViewUsers { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AccountManagementGranular {\n");
            sb.Append("  AllowManageAccountSecuritySettings: ").Append(AllowManageAccountSecuritySettings).Append("\n");
            sb.Append("  AllowManageAccountSecuritySettingsMetadata: ").Append(AllowManageAccountSecuritySettingsMetadata).Append("\n");
            sb.Append("  AllowManageAccountSettings: ").Append(AllowManageAccountSettings).Append("\n");
            sb.Append("  AllowManageAccountSettingsMetadata: ").Append(AllowManageAccountSettingsMetadata).Append("\n");
            sb.Append("  AllowManageAdmins: ").Append(AllowManageAdmins).Append("\n");
            sb.Append("  AllowManageAdminsMetadata: ").Append(AllowManageAdminsMetadata).Append("\n");
            sb.Append("  AllowManageConnect: ").Append(AllowManageConnect).Append("\n");
            sb.Append("  AllowManageConnectMetadata: ").Append(AllowManageConnectMetadata).Append("\n");
            sb.Append("  AllowManageDocumentRetention: ").Append(AllowManageDocumentRetention).Append("\n");
            sb.Append("  AllowManageDocumentRetentionMetadata: ").Append(AllowManageDocumentRetentionMetadata).Append("\n");
            sb.Append("  AllowManageEnvelopeTransfer: ").Append(AllowManageEnvelopeTransfer).Append("\n");
            sb.Append("  AllowManageEnvelopeTransferMetadata: ").Append(AllowManageEnvelopeTransferMetadata).Append("\n");
            sb.Append("  AllowManageGroupsButNotUsers: ").Append(AllowManageGroupsButNotUsers).Append("\n");
            sb.Append("  AllowManageGroupsButNotUsersMetadata: ").Append(AllowManageGroupsButNotUsersMetadata).Append("\n");
            sb.Append("  AllowManageJointAgreements: ").Append(AllowManageJointAgreements).Append("\n");
            sb.Append("  AllowManageJointAgreementsMetadata: ").Append(AllowManageJointAgreementsMetadata).Append("\n");
            sb.Append("  AllowManageReporting: ").Append(AllowManageReporting).Append("\n");
            sb.Append("  AllowManageReportingMetadata: ").Append(AllowManageReportingMetadata).Append("\n");
            sb.Append("  AllowManageSharing: ").Append(AllowManageSharing).Append("\n");
            sb.Append("  AllowManageSharingMetadata: ").Append(AllowManageSharingMetadata).Append("\n");
            sb.Append("  AllowManageSigningGroups: ").Append(AllowManageSigningGroups).Append("\n");
            sb.Append("  AllowManageSigningGroupsMetadata: ").Append(AllowManageSigningGroupsMetadata).Append("\n");
            sb.Append("  AllowManageStamps: ").Append(AllowManageStamps).Append("\n");
            sb.Append("  AllowManageStampsMetadata: ").Append(AllowManageStampsMetadata).Append("\n");
            sb.Append("  AllowManageUsers: ").Append(AllowManageUsers).Append("\n");
            sb.Append("  AllowManageUsersMetadata: ").Append(AllowManageUsersMetadata).Append("\n");
            sb.Append("  AllowViewUsers: ").Append(AllowViewUsers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AccountManagementGranular);
        }

        /// <summary>
        /// Returns true if AccountManagementGranular instances are equal
        /// </summary>
        /// <param name="other">Instance of AccountManagementGranular to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountManagementGranular other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.AllowManageAccountSecuritySettings == other.AllowManageAccountSecuritySettings ||
                    this.AllowManageAccountSecuritySettings != null &&
                    this.AllowManageAccountSecuritySettings.Equals(other.AllowManageAccountSecuritySettings)
                ) && 
                (
                    this.AllowManageAccountSecuritySettingsMetadata == other.AllowManageAccountSecuritySettingsMetadata ||
                    this.AllowManageAccountSecuritySettingsMetadata != null &&
                    this.AllowManageAccountSecuritySettingsMetadata.Equals(other.AllowManageAccountSecuritySettingsMetadata)
                ) && 
                (
                    this.AllowManageAccountSettings == other.AllowManageAccountSettings ||
                    this.AllowManageAccountSettings != null &&
                    this.AllowManageAccountSettings.Equals(other.AllowManageAccountSettings)
                ) && 
                (
                    this.AllowManageAccountSettingsMetadata == other.AllowManageAccountSettingsMetadata ||
                    this.AllowManageAccountSettingsMetadata != null &&
                    this.AllowManageAccountSettingsMetadata.Equals(other.AllowManageAccountSettingsMetadata)
                ) && 
                (
                    this.AllowManageAdmins == other.AllowManageAdmins ||
                    this.AllowManageAdmins != null &&
                    this.AllowManageAdmins.Equals(other.AllowManageAdmins)
                ) && 
                (
                    this.AllowManageAdminsMetadata == other.AllowManageAdminsMetadata ||
                    this.AllowManageAdminsMetadata != null &&
                    this.AllowManageAdminsMetadata.Equals(other.AllowManageAdminsMetadata)
                ) && 
                (
                    this.AllowManageConnect == other.AllowManageConnect ||
                    this.AllowManageConnect != null &&
                    this.AllowManageConnect.Equals(other.AllowManageConnect)
                ) && 
                (
                    this.AllowManageConnectMetadata == other.AllowManageConnectMetadata ||
                    this.AllowManageConnectMetadata != null &&
                    this.AllowManageConnectMetadata.Equals(other.AllowManageConnectMetadata)
                ) && 
                (
                    this.AllowManageDocumentRetention == other.AllowManageDocumentRetention ||
                    this.AllowManageDocumentRetention != null &&
                    this.AllowManageDocumentRetention.Equals(other.AllowManageDocumentRetention)
                ) && 
                (
                    this.AllowManageDocumentRetentionMetadata == other.AllowManageDocumentRetentionMetadata ||
                    this.AllowManageDocumentRetentionMetadata != null &&
                    this.AllowManageDocumentRetentionMetadata.Equals(other.AllowManageDocumentRetentionMetadata)
                ) && 
                (
                    this.AllowManageEnvelopeTransfer == other.AllowManageEnvelopeTransfer ||
                    this.AllowManageEnvelopeTransfer != null &&
                    this.AllowManageEnvelopeTransfer.Equals(other.AllowManageEnvelopeTransfer)
                ) && 
                (
                    this.AllowManageEnvelopeTransferMetadata == other.AllowManageEnvelopeTransferMetadata ||
                    this.AllowManageEnvelopeTransferMetadata != null &&
                    this.AllowManageEnvelopeTransferMetadata.Equals(other.AllowManageEnvelopeTransferMetadata)
                ) && 
                (
                    this.AllowManageGroupsButNotUsers == other.AllowManageGroupsButNotUsers ||
                    this.AllowManageGroupsButNotUsers != null &&
                    this.AllowManageGroupsButNotUsers.Equals(other.AllowManageGroupsButNotUsers)
                ) && 
                (
                    this.AllowManageGroupsButNotUsersMetadata == other.AllowManageGroupsButNotUsersMetadata ||
                    this.AllowManageGroupsButNotUsersMetadata != null &&
                    this.AllowManageGroupsButNotUsersMetadata.Equals(other.AllowManageGroupsButNotUsersMetadata)
                ) && 
                (
                    this.AllowManageJointAgreements == other.AllowManageJointAgreements ||
                    this.AllowManageJointAgreements != null &&
                    this.AllowManageJointAgreements.Equals(other.AllowManageJointAgreements)
                ) && 
                (
                    this.AllowManageJointAgreementsMetadata == other.AllowManageJointAgreementsMetadata ||
                    this.AllowManageJointAgreementsMetadata != null &&
                    this.AllowManageJointAgreementsMetadata.Equals(other.AllowManageJointAgreementsMetadata)
                ) && 
                (
                    this.AllowManageReporting == other.AllowManageReporting ||
                    this.AllowManageReporting != null &&
                    this.AllowManageReporting.Equals(other.AllowManageReporting)
                ) && 
                (
                    this.AllowManageReportingMetadata == other.AllowManageReportingMetadata ||
                    this.AllowManageReportingMetadata != null &&
                    this.AllowManageReportingMetadata.Equals(other.AllowManageReportingMetadata)
                ) && 
                (
                    this.AllowManageSharing == other.AllowManageSharing ||
                    this.AllowManageSharing != null &&
                    this.AllowManageSharing.Equals(other.AllowManageSharing)
                ) && 
                (
                    this.AllowManageSharingMetadata == other.AllowManageSharingMetadata ||
                    this.AllowManageSharingMetadata != null &&
                    this.AllowManageSharingMetadata.Equals(other.AllowManageSharingMetadata)
                ) && 
                (
                    this.AllowManageSigningGroups == other.AllowManageSigningGroups ||
                    this.AllowManageSigningGroups != null &&
                    this.AllowManageSigningGroups.Equals(other.AllowManageSigningGroups)
                ) && 
                (
                    this.AllowManageSigningGroupsMetadata == other.AllowManageSigningGroupsMetadata ||
                    this.AllowManageSigningGroupsMetadata != null &&
                    this.AllowManageSigningGroupsMetadata.Equals(other.AllowManageSigningGroupsMetadata)
                ) && 
                (
                    this.AllowManageStamps == other.AllowManageStamps ||
                    this.AllowManageStamps != null &&
                    this.AllowManageStamps.Equals(other.AllowManageStamps)
                ) && 
                (
                    this.AllowManageStampsMetadata == other.AllowManageStampsMetadata ||
                    this.AllowManageStampsMetadata != null &&
                    this.AllowManageStampsMetadata.Equals(other.AllowManageStampsMetadata)
                ) && 
                (
                    this.AllowManageUsers == other.AllowManageUsers ||
                    this.AllowManageUsers != null &&
                    this.AllowManageUsers.Equals(other.AllowManageUsers)
                ) && 
                (
                    this.AllowManageUsersMetadata == other.AllowManageUsersMetadata ||
                    this.AllowManageUsersMetadata != null &&
                    this.AllowManageUsersMetadata.Equals(other.AllowManageUsersMetadata)
                ) && 
                (
                    this.AllowViewUsers == other.AllowViewUsers ||
                    this.AllowViewUsers != null &&
                    this.AllowViewUsers.Equals(other.AllowViewUsers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.AllowManageAccountSecuritySettings != null)
                    hash = hash * 59 + this.AllowManageAccountSecuritySettings.GetHashCode();
                if (this.AllowManageAccountSecuritySettingsMetadata != null)
                    hash = hash * 59 + this.AllowManageAccountSecuritySettingsMetadata.GetHashCode();
                if (this.AllowManageAccountSettings != null)
                    hash = hash * 59 + this.AllowManageAccountSettings.GetHashCode();
                if (this.AllowManageAccountSettingsMetadata != null)
                    hash = hash * 59 + this.AllowManageAccountSettingsMetadata.GetHashCode();
                if (this.AllowManageAdmins != null)
                    hash = hash * 59 + this.AllowManageAdmins.GetHashCode();
                if (this.AllowManageAdminsMetadata != null)
                    hash = hash * 59 + this.AllowManageAdminsMetadata.GetHashCode();
                if (this.AllowManageConnect != null)
                    hash = hash * 59 + this.AllowManageConnect.GetHashCode();
                if (this.AllowManageConnectMetadata != null)
                    hash = hash * 59 + this.AllowManageConnectMetadata.GetHashCode();
                if (this.AllowManageDocumentRetention != null)
                    hash = hash * 59 + this.AllowManageDocumentRetention.GetHashCode();
                if (this.AllowManageDocumentRetentionMetadata != null)
                    hash = hash * 59 + this.AllowManageDocumentRetentionMetadata.GetHashCode();
                if (this.AllowManageEnvelopeTransfer != null)
                    hash = hash * 59 + this.AllowManageEnvelopeTransfer.GetHashCode();
                if (this.AllowManageEnvelopeTransferMetadata != null)
                    hash = hash * 59 + this.AllowManageEnvelopeTransferMetadata.GetHashCode();
                if (this.AllowManageGroupsButNotUsers != null)
                    hash = hash * 59 + this.AllowManageGroupsButNotUsers.GetHashCode();
                if (this.AllowManageGroupsButNotUsersMetadata != null)
                    hash = hash * 59 + this.AllowManageGroupsButNotUsersMetadata.GetHashCode();
                if (this.AllowManageJointAgreements != null)
                    hash = hash * 59 + this.AllowManageJointAgreements.GetHashCode();
                if (this.AllowManageJointAgreementsMetadata != null)
                    hash = hash * 59 + this.AllowManageJointAgreementsMetadata.GetHashCode();
                if (this.AllowManageReporting != null)
                    hash = hash * 59 + this.AllowManageReporting.GetHashCode();
                if (this.AllowManageReportingMetadata != null)
                    hash = hash * 59 + this.AllowManageReportingMetadata.GetHashCode();
                if (this.AllowManageSharing != null)
                    hash = hash * 59 + this.AllowManageSharing.GetHashCode();
                if (this.AllowManageSharingMetadata != null)
                    hash = hash * 59 + this.AllowManageSharingMetadata.GetHashCode();
                if (this.AllowManageSigningGroups != null)
                    hash = hash * 59 + this.AllowManageSigningGroups.GetHashCode();
                if (this.AllowManageSigningGroupsMetadata != null)
                    hash = hash * 59 + this.AllowManageSigningGroupsMetadata.GetHashCode();
                if (this.AllowManageStamps != null)
                    hash = hash * 59 + this.AllowManageStamps.GetHashCode();
                if (this.AllowManageStampsMetadata != null)
                    hash = hash * 59 + this.AllowManageStampsMetadata.GetHashCode();
                if (this.AllowManageUsers != null)
                    hash = hash * 59 + this.AllowManageUsers.GetHashCode();
                if (this.AllowManageUsersMetadata != null)
                    hash = hash * 59 + this.AllowManageUsersMetadata.GetHashCode();
                if (this.AllowViewUsers != null)
                    hash = hash * 59 + this.AllowViewUsers.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }
}
