/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using DocuSign.eSign.Client;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing NotaryApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NotaryApiTests
    {
        private NotaryApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NotaryApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotaryApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NotaryApi
            //Assert.IsInstanceOfType(typeof(NotaryApi), instance, "instance is a NotaryApi");
        }

        
        /// <summary>
        /// Test ListNotaryJournals
        /// </summary>
        [Test]
        public void ListNotaryJournalsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string count = null;
            //string searchText = null;
            //string startPosition = null;
            //var response = instance.ListNotaryJournals(count, searchText, startPosition);
            //Assert.IsInstanceOf<NotaryJournalList> (response, "response is NotaryJournalList");
        }
        
    }

}
