/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using DocuSign.eSign.Client;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing AccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AccountsApiTests
    {
        private AccountsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AccountsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AccountsApi
            //Assert.IsInstanceOfType(typeof(AccountsApi), instance, "instance is a AccountsApi");
        }

        
        /// <summary>
        /// Test Create
        /// </summary>
        [Test]
        public void CreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string previewBillingPlan = null;
            //NewAccountDefinition newAccountDefinition = null;
            //var response = instance.Create(previewBillingPlan, newAccountDefinition);
            //Assert.IsInstanceOf<NewAccountSummary> (response, "response is NewAccountSummary");
        }
        
        /// <summary>
        /// Test CreateBrand
        /// </summary>
        [Test]
        public void CreateBrandTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //Brand brand = null;
            //var response = instance.CreateBrand(accountId, brand);
            //Assert.IsInstanceOf<BrandsResponse> (response, "response is BrandsResponse");
        }
        
        /// <summary>
        /// Test CreateEMortgageTransaction
        /// </summary>
        [Test]
        public void CreateEMortgageTransactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //PostTransactionsRequest postTransactionsRequest = null;
            //var response = instance.CreateEMortgageTransaction(accountId, postTransactionsRequest);
            //Assert.IsInstanceOf<PostTransactionsResponse> (response, "response is PostTransactionsResponse");
        }
        
        /// <summary>
        /// Test CreatePermissionProfile
        /// </summary>
        [Test]
        public void CreatePermissionProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string include = null;
            //PermissionProfile permissionProfile = null;
            //var response = instance.CreatePermissionProfile(accountId, include, permissionProfile);
            //Assert.IsInstanceOf<PermissionProfile> (response, "response is PermissionProfile");
        }
        
        /// <summary>
        /// Test Delete
        /// </summary>
        [Test]
        public void DeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //instance.Delete(accountId);
            
        }
        
        /// <summary>
        /// Test DeleteBrand
        /// </summary>
        [Test]
        public void DeleteBrandTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //instance.DeleteBrand(accountId, brandId);
            
        }
        
        /// <summary>
        /// Test DeleteBrandLogoByType
        /// </summary>
        [Test]
        public void DeleteBrandLogoByTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //string logoType = null;
            //instance.DeleteBrandLogoByType(accountId, brandId, logoType);
            
        }
        
        /// <summary>
        /// Test DeleteBrands
        /// </summary>
        [Test]
        public void DeleteBrandsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //BrandsRequest brandsRequest = null;
            //var response = instance.DeleteBrands(accountId, brandsRequest);
            //Assert.IsInstanceOf<BrandsResponse> (response, "response is BrandsResponse");
        }
        
        /// <summary>
        /// Test DeleteCaptiveRecipient
        /// </summary>
        [Test]
        public void DeleteCaptiveRecipientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string recipientPart = null;
            //CaptiveRecipientInformation captiveRecipientInformation = null;
            //var response = instance.DeleteCaptiveRecipient(accountId, recipientPart, captiveRecipientInformation);
            //Assert.IsInstanceOf<CaptiveRecipientInformation> (response, "response is CaptiveRecipientInformation");
        }
        
        /// <summary>
        /// Test DeleteENoteConfiguration
        /// </summary>
        [Test]
        public void DeleteENoteConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //instance.DeleteENoteConfiguration(accountId);
            
        }
        
        /// <summary>
        /// Test DeletePermissionProfile
        /// </summary>
        [Test]
        public void DeletePermissionProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string permissionProfileId = null;
            //instance.DeletePermissionProfile(accountId, permissionProfileId);
            
        }
        
        /// <summary>
        /// Test GetAccountInformation
        /// </summary>
        [Test]
        public void GetAccountInformationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string includeAccountSettings = null;
            //var response = instance.GetAccountInformation(accountId, includeAccountSettings);
            //Assert.IsInstanceOf<AccountInformation> (response, "response is AccountInformation");
        }
        
        /// <summary>
        /// Test GetAccountTabSettings
        /// </summary>
        [Test]
        public void GetAccountTabSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.GetAccountTabSettings(accountId);
            //Assert.IsInstanceOf<TabAccountSettings> (response, "response is TabAccountSettings");
        }
        
        /// <summary>
        /// Test GetBillingCharges
        /// </summary>
        [Test]
        public void GetBillingChargesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string includeCharges = null;
            //var response = instance.GetBillingCharges(accountId, includeCharges);
            //Assert.IsInstanceOf<BillingChargeResponse> (response, "response is BillingChargeResponse");
        }
        
        /// <summary>
        /// Test GetBrand
        /// </summary>
        [Test]
        public void GetBrandTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //string includeExternalReferences = null;
            //string includeLogos = null;
            //var response = instance.GetBrand(accountId, brandId, includeExternalReferences, includeLogos);
            //Assert.IsInstanceOf<Brand> (response, "response is Brand");
        }
        
        /// <summary>
        /// Test GetBrandLogoByType
        /// </summary>
        [Test]
        public void GetBrandLogoByTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //string logoType = null;
            //instance.GetBrandLogoByType(accountId, brandId, logoType);
            
        }
        
        /// <summary>
        /// Test GetBrandResources
        /// </summary>
        [Test]
        public void GetBrandResourcesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //var response = instance.GetBrandResources(accountId, brandId);
            //Assert.IsInstanceOf<BrandResourcesList> (response, "response is BrandResourcesList");
        }
        
        /// <summary>
        /// Test GetBrandResourcesByContentType
        /// </summary>
        [Test]
        public void GetBrandResourcesByContentTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //string resourceContentType = null;
            //string langcode = null;
            //string returnMaster = null;
            //instance.GetBrandResourcesByContentType(accountId, brandId, resourceContentType, langcode, returnMaster);
            
        }
        
        /// <summary>
        /// Test GetConsumerDisclosure
        /// </summary>
        [Test]
        public void GetConsumerDisclosureTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string langCode = null;
            //var response = instance.GetConsumerDisclosure(accountId, langCode);
            //Assert.IsInstanceOf<ConsumerDisclosure> (response, "response is ConsumerDisclosure");
        }
        
        /// <summary>
        /// Test GetConsumerDisclosureDefault
        /// </summary>
        [Test]
        public void GetConsumerDisclosureDefaultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string langCode = null;
            //var response = instance.GetConsumerDisclosureDefault(accountId, langCode);
            //Assert.IsInstanceOf<ConsumerDisclosure> (response, "response is ConsumerDisclosure");
        }
        
        /// <summary>
        /// Test GetENoteConfiguration
        /// </summary>
        [Test]
        public void GetENoteConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.GetENoteConfiguration(accountId);
            //Assert.IsInstanceOf<ENoteConfiguration> (response, "response is ENoteConfiguration");
        }
        
        /// <summary>
        /// Test GetPermissionProfile
        /// </summary>
        [Test]
        public void GetPermissionProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string permissionProfileId = null;
            //string include = null;
            //var response = instance.GetPermissionProfile(accountId, permissionProfileId, include);
            //Assert.IsInstanceOf<PermissionProfile> (response, "response is PermissionProfile");
        }
        
        /// <summary>
        /// Test GetProvisioning
        /// </summary>
        [Test]
        public void GetProvisioningTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetProvisioning();
            //Assert.IsInstanceOf<ProvisioningInformation> (response, "response is ProvisioningInformation");
        }
        
        /// <summary>
        /// Test ListBrands
        /// </summary>
        [Test]
        public void ListBrandsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string excludeDistributorBrand = null;
            //string includeLogos = null;
            //var response = instance.ListBrands(accountId, excludeDistributorBrand, includeLogos);
            //Assert.IsInstanceOf<BrandsResponse> (response, "response is BrandsResponse");
        }
        
        /// <summary>
        /// Test ListCustomFields
        /// </summary>
        [Test]
        public void ListCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.ListCustomFields(accountId);
            //Assert.IsInstanceOf<CustomFields> (response, "response is CustomFields");
        }
        
        /// <summary>
        /// Test ListPermissions
        /// </summary>
        [Test]
        public void ListPermissionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string include = null;
            //var response = instance.ListPermissions(accountId, include);
            //Assert.IsInstanceOf<PermissionProfileInformation> (response, "response is PermissionProfileInformation");
        }
        
        /// <summary>
        /// Test ListRecipientNamesByEmail
        /// </summary>
        [Test]
        public void ListRecipientNamesByEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string email = null;
            //var response = instance.ListRecipientNamesByEmail(accountId, email);
            //Assert.IsInstanceOf<RecipientNamesResponse> (response, "response is RecipientNamesResponse");
        }
        
        /// <summary>
        /// Test ListSettings
        /// </summary>
        [Test]
        public void ListSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.ListSettings(accountId);
            //Assert.IsInstanceOf<AccountSettingsInformation> (response, "response is AccountSettingsInformation");
        }
        
        /// <summary>
        /// Test ListSharedAccess
        /// </summary>
        [Test]
        public void ListSharedAccessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string count = null;
            //string envelopesNotSharedUserStatus = null;
            //string folderIds = null;
            //string itemType = null;
            //string searchText = null;
            //string shared = null;
            //string startPosition = null;
            //string userIds = null;
            //var response = instance.ListSharedAccess(accountId, count, envelopesNotSharedUserStatus, folderIds, itemType, searchText, shared, startPosition, userIds);
            //Assert.IsInstanceOf<AccountSharedAccess> (response, "response is AccountSharedAccess");
        }
        
        /// <summary>
        /// Test ListSignatureProviders
        /// </summary>
        [Test]
        public void ListSignatureProvidersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.ListSignatureProviders(accountId);
            //Assert.IsInstanceOf<AccountSignatureProviders> (response, "response is AccountSignatureProviders");
        }
        
        /// <summary>
        /// Test ListUnsupportedFileTypes
        /// </summary>
        [Test]
        public void ListUnsupportedFileTypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.ListUnsupportedFileTypes(accountId);
            //Assert.IsInstanceOf<FileTypeList> (response, "response is FileTypeList");
        }
        
        /// <summary>
        /// Test UpdateAccountTabSettings
        /// </summary>
        [Test]
        public void UpdateAccountTabSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //TabAccountSettings tabAccountSettings = null;
            //var response = instance.UpdateAccountTabSettings(accountId, tabAccountSettings);
            //Assert.IsInstanceOf<TabAccountSettings> (response, "response is TabAccountSettings");
        }
        
        /// <summary>
        /// Test UpdateBrand
        /// </summary>
        [Test]
        public void UpdateBrandTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //Brand brand = null;
            //var response = instance.UpdateBrand(accountId, brandId, brand);
            //Assert.IsInstanceOf<Brand> (response, "response is Brand");
        }
        
        /// <summary>
        /// Test UpdateBrandLogoByType
        /// </summary>
        [Test]
        public void UpdateBrandLogoByTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //string logoType = null;
            //instance.UpdateBrandLogoByType(accountId, brandId, logoType);
            
        }
        
        /// <summary>
        /// Test UpdateBrandResourcesByContentType
        /// </summary>
        [Test]
        public void UpdateBrandResourcesByContentTypeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string brandId = null;
            //string resourceContentType = null;
            //var response = instance.UpdateBrandResourcesByContentType(accountId, brandId, resourceContentType);
            //Assert.IsInstanceOf<BrandResources> (response, "response is BrandResources");
        }
        
        /// <summary>
        /// Test UpdateENoteConfiguration
        /// </summary>
        [Test]
        public void UpdateENoteConfigurationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //ENoteConfiguration eNoteConfiguration = null;
            //var response = instance.UpdateENoteConfiguration(accountId, eNoteConfiguration);
            //Assert.IsInstanceOf<ENoteConfiguration> (response, "response is ENoteConfiguration");
        }
        
        /// <summary>
        /// Test UpdatePermissionProfile
        /// </summary>
        [Test]
        public void UpdatePermissionProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string permissionProfileId = null;
            //string include = null;
            //PermissionProfile permissionProfile = null;
            //var response = instance.UpdatePermissionProfile(accountId, permissionProfileId, include, permissionProfile);
            //Assert.IsInstanceOf<PermissionProfile> (response, "response is PermissionProfile");
        }
        
        /// <summary>
        /// Test UpdateSettings
        /// </summary>
        [Test]
        public void UpdateSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //AccountSettingsInformation accountSettingsInformation = null;
            //instance.UpdateSettings(accountId, accountSettingsInformation);
            
        }
        
        /// <summary>
        /// Test UpdateSharedAccess
        /// </summary>
        [Test]
        public void UpdateSharedAccessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string itemType = null;
            //string userIds = null;
            //AccountSharedAccess accountSharedAccess = null;
            //var response = instance.UpdateSharedAccess(accountId, itemType, userIds, accountSharedAccess);
            //Assert.IsInstanceOf<AccountSharedAccess> (response, "response is AccountSharedAccess");
        }
        
    }

}
