/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using DocuSign.eSign.Client;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing EnvelopesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvelopesApiTests
    {
        private EnvelopesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EnvelopesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvelopesApi
            //Assert.IsInstanceOfType(typeof(EnvelopesApi), instance, "instance is a EnvelopesApi");
        }

        
        /// <summary>
        /// Test ApplyTemplate
        /// </summary>
        [Test]
        public void ApplyTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //DocumentTemplateList documentTemplateList = null;
            //var response = instance.ApplyTemplate(accountId, envelopeId, documentTemplateList);
            //Assert.IsInstanceOf<DocumentTemplateList> (response, "response is DocumentTemplateList");
        }
        
        /// <summary>
        /// Test ApplyTemplateToDocument
        /// </summary>
        [Test]
        public void ApplyTemplateToDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //DocumentTemplateList documentTemplateList = null;
            //var response = instance.ApplyTemplateToDocument(accountId, documentId, envelopeId, documentTemplateList);
            //Assert.IsInstanceOf<DocumentTemplateList> (response, "response is DocumentTemplateList");
        }
        
        /// <summary>
        /// Test CreateChunkedUpload
        /// </summary>
        [Test]
        public void CreateChunkedUploadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //ChunkedUploadRequest chunkedUploadRequest = null;
            //var response = instance.CreateChunkedUpload(accountId, chunkedUploadRequest);
            //Assert.IsInstanceOf<ChunkedUploadResponse> (response, "response is ChunkedUploadResponse");
        }
        
        /// <summary>
        /// Test CreateConsoleView
        /// </summary>
        [Test]
        public void CreateConsoleViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //ConsoleViewRequest consoleViewRequest = null;
            //var response = instance.CreateConsoleView(accountId, consoleViewRequest);
            //Assert.IsInstanceOf<ViewUrl> (response, "response is ViewUrl");
        }
        
        /// <summary>
        /// Test CreateCorrectView
        /// </summary>
        [Test]
        public void CreateCorrectViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //CorrectViewRequest correctViewRequest = null;
            //var response = instance.CreateCorrectView(accountId, envelopeId, correctViewRequest);
            //Assert.IsInstanceOf<ViewUrl> (response, "response is ViewUrl");
        }
        
        /// <summary>
        /// Test CreateCustomFields
        /// </summary>
        [Test]
        public void CreateCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //CustomFields customFields = null;
            //var response = instance.CreateCustomFields(accountId, envelopeId, customFields);
            //Assert.IsInstanceOf<CustomFields> (response, "response is CustomFields");
        }
        
        /// <summary>
        /// Test CreateDocumentFields
        /// </summary>
        [Test]
        public void CreateDocumentFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //DocumentFieldsInformation documentFieldsInformation = null;
            //var response = instance.CreateDocumentFields(accountId, documentId, envelopeId, documentFieldsInformation);
            //Assert.IsInstanceOf<DocumentFieldsInformation> (response, "response is DocumentFieldsInformation");
        }
        
        /// <summary>
        /// Test CreateEditView
        /// </summary>
        [Test]
        public void CreateEditViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //ReturnUrlRequest returnUrlRequest = null;
            //var response = instance.CreateEditView(accountId, envelopeId, returnUrlRequest);
            //Assert.IsInstanceOf<ViewUrl> (response, "response is ViewUrl");
        }
        
        /// <summary>
        /// Test CreateEmailSettings
        /// </summary>
        [Test]
        public void CreateEmailSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EmailSettings emailSettings = null;
            //var response = instance.CreateEmailSettings(accountId, envelopeId, emailSettings);
            //Assert.IsInstanceOf<EmailSettings> (response, "response is EmailSettings");
        }
        
        /// <summary>
        /// Test CreateEnvelope
        /// </summary>
        [Test]
        public void CreateEnvelopeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string cdseMode = null;
            //string completedDocumentsOnly = null;
            //string mergeRolesOnDraft = null;
            //EnvelopeDefinition envelopeDefinition = null;
            //var response = instance.CreateEnvelope(accountId, cdseMode, completedDocumentsOnly, mergeRolesOnDraft, envelopeDefinition);
            //Assert.IsInstanceOf<EnvelopeSummary> (response, "response is EnvelopeSummary");
        }
        
        /// <summary>
        /// Test CreateLock
        /// </summary>
        [Test]
        public void CreateLockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //LockRequest lockRequest = null;
            //var response = instance.CreateLock(accountId, envelopeId, lockRequest);
            //Assert.IsInstanceOf<LockInformation> (response, "response is LockInformation");
        }
        
        /// <summary>
        /// Test CreateRecipient
        /// </summary>
        [Test]
        public void CreateRecipientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string resendEnvelope = null;
            //Recipients recipients = null;
            //var response = instance.CreateRecipient(accountId, envelopeId, resendEnvelope, recipients);
            //Assert.IsInstanceOf<Recipients> (response, "response is Recipients");
        }
        
        /// <summary>
        /// Test CreateRecipientView
        /// </summary>
        [Test]
        public void CreateRecipientViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //RecipientViewRequest recipientViewRequest = null;
            //var response = instance.CreateRecipientView(accountId, envelopeId, recipientViewRequest);
            //Assert.IsInstanceOf<ViewUrl> (response, "response is ViewUrl");
        }
        
        /// <summary>
        /// Test CreateSenderView
        /// </summary>
        [Test]
        public void CreateSenderViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //ReturnUrlRequest returnUrlRequest = null;
            //var response = instance.CreateSenderView(accountId, envelopeId, returnUrlRequest);
            //Assert.IsInstanceOf<ViewUrl> (response, "response is ViewUrl");
        }
        
        /// <summary>
        /// Test CreateTabs
        /// </summary>
        [Test]
        public void CreateTabsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //Tabs tabs = null;
            //var response = instance.CreateTabs(accountId, envelopeId, recipientId, tabs);
            //Assert.IsInstanceOf<Tabs> (response, "response is Tabs");
        }
        
        /// <summary>
        /// Test CreateViewLink
        /// </summary>
        [Test]
        public void CreateViewLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //ViewLinkRequest viewLinkRequest = null;
            //var response = instance.CreateViewLink(accountId, envelopeId, viewLinkRequest);
            //Assert.IsInstanceOf<ViewUrl> (response, "response is ViewUrl");
        }
        
        /// <summary>
        /// Test DeleteAttachments
        /// </summary>
        [Test]
        public void DeleteAttachmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeAttachmentsRequest envelopeAttachmentsRequest = null;
            //var response = instance.DeleteAttachments(accountId, envelopeId, envelopeAttachmentsRequest);
            //Assert.IsInstanceOf<EnvelopeAttachmentsResult> (response, "response is EnvelopeAttachmentsResult");
        }
        
        /// <summary>
        /// Test DeleteChunkedUpload
        /// </summary>
        [Test]
        public void DeleteChunkedUploadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string chunkedUploadId = null;
            //var response = instance.DeleteChunkedUpload(accountId, chunkedUploadId);
            //Assert.IsInstanceOf<ChunkedUploadResponse> (response, "response is ChunkedUploadResponse");
        }
        
        /// <summary>
        /// Test DeleteCustomFields
        /// </summary>
        [Test]
        public void DeleteCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //CustomFields customFields = null;
            //var response = instance.DeleteCustomFields(accountId, envelopeId, customFields);
            //Assert.IsInstanceOf<CustomFields> (response, "response is CustomFields");
        }
        
        /// <summary>
        /// Test DeleteDocumentFields
        /// </summary>
        [Test]
        public void DeleteDocumentFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //DocumentFieldsInformation documentFieldsInformation = null;
            //var response = instance.DeleteDocumentFields(accountId, documentId, envelopeId, documentFieldsInformation);
            //Assert.IsInstanceOf<DocumentFieldsInformation> (response, "response is DocumentFieldsInformation");
        }
        
        /// <summary>
        /// Test DeleteDocumentPage
        /// </summary>
        [Test]
        public void DeleteDocumentPageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //string pageNumber = null;
            //instance.DeleteDocumentPage(accountId, documentId, envelopeId, pageNumber);
            
        }
        
        /// <summary>
        /// Test DeleteDocuments
        /// </summary>
        [Test]
        public void DeleteDocumentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeDefinition envelopeDefinition = null;
            //var response = instance.DeleteDocuments(accountId, envelopeId, envelopeDefinition);
            //Assert.IsInstanceOf<EnvelopeDocumentsResult> (response, "response is EnvelopeDocumentsResult");
        }
        
        /// <summary>
        /// Test DeleteEmailSettings
        /// </summary>
        [Test]
        public void DeleteEmailSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.DeleteEmailSettings(accountId, envelopeId);
            //Assert.IsInstanceOf<EmailSettings> (response, "response is EmailSettings");
        }
        
        /// <summary>
        /// Test DeleteLock
        /// </summary>
        [Test]
        public void DeleteLockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.DeleteLock(accountId, envelopeId);
            //Assert.IsInstanceOf<LockInformation> (response, "response is LockInformation");
        }
        
        /// <summary>
        /// Test DeleteRecipient
        /// </summary>
        [Test]
        public void DeleteRecipientTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //var response = instance.DeleteRecipient(accountId, envelopeId, recipientId);
            //Assert.IsInstanceOf<Recipients> (response, "response is Recipients");
        }
        
        /// <summary>
        /// Test DeleteRecipients
        /// </summary>
        [Test]
        public void DeleteRecipientsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //Recipients recipients = null;
            //var response = instance.DeleteRecipients(accountId, envelopeId, recipients);
            //Assert.IsInstanceOf<Recipients> (response, "response is Recipients");
        }
        
        /// <summary>
        /// Test DeleteTabs
        /// </summary>
        [Test]
        public void DeleteTabsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //Tabs tabs = null;
            //var response = instance.DeleteTabs(accountId, envelopeId, recipientId, tabs);
            //Assert.IsInstanceOf<Tabs> (response, "response is Tabs");
        }
        
        /// <summary>
        /// Test DeleteTemplatesFromDocument
        /// </summary>
        [Test]
        public void DeleteTemplatesFromDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //string templateId = null;
            //instance.DeleteTemplatesFromDocument(accountId, documentId, envelopeId, templateId);
            
        }
        
        /// <summary>
        /// Test DeleteViewLink
        /// </summary>
        [Test]
        public void DeleteViewLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //instance.DeleteViewLink(accountId, envelopeId);
            
        }
        
        /// <summary>
        /// Test GetAttachment
        /// </summary>
        [Test]
        public void GetAttachmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string attachmentId = null;
            //string envelopeId = null;
            //instance.GetAttachment(accountId, attachmentId, envelopeId);
            
        }
        
        /// <summary>
        /// Test GetAttachments
        /// </summary>
        [Test]
        public void GetAttachmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.GetAttachments(accountId, envelopeId);
            //Assert.IsInstanceOf<EnvelopeAttachmentsResult> (response, "response is EnvelopeAttachmentsResult");
        }
        
        /// <summary>
        /// Test GetChunkedUpload
        /// </summary>
        [Test]
        public void GetChunkedUploadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string chunkedUploadId = null;
            //string include = null;
            //var response = instance.GetChunkedUpload(accountId, chunkedUploadId, include);
            //Assert.IsInstanceOf<ChunkedUploadResponse> (response, "response is ChunkedUploadResponse");
        }
        
        /// <summary>
        /// Test GetConsumerDisclosure
        /// </summary>
        [Test]
        public void GetConsumerDisclosureTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string langCode = null;
            //string recipientId = null;
            //string langCode2 = null;
            //var response = instance.GetConsumerDisclosure(accountId, envelopeId, langCode, recipientId, langCode2);
            //Assert.IsInstanceOf<ConsumerDisclosure> (response, "response is ConsumerDisclosure");
        }
        
        /// <summary>
        /// Test GetConsumerDisclosureDefault
        /// </summary>
        [Test]
        public void GetConsumerDisclosureDefaultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //string langCode = null;
            //var response = instance.GetConsumerDisclosureDefault(accountId, envelopeId, recipientId, langCode);
            //Assert.IsInstanceOf<ConsumerDisclosure> (response, "response is ConsumerDisclosure");
        }
        
        /// <summary>
        /// Test GetDocument
        /// </summary>
        [Test]
        public void GetDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //string certificate = null;
            //string encoding = null;
            //string encrypt = null;
            //string language = null;
            //string recipientId = null;
            //string showChanges = null;
            //string watermark = null;
            //var response = instance.GetDocument(accountId, documentId, envelopeId, certificate, encoding, encrypt, language, recipientId, showChanges, watermark);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetDocumentPageImage
        /// </summary>
        [Test]
        public void GetDocumentPageImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //string pageNumber = null;
            //string dpi = null;
            //string maxHeight = null;
            //string maxWidth = null;
            //string showChanges = null;
            //var response = instance.GetDocumentPageImage(accountId, documentId, envelopeId, pageNumber, dpi, maxHeight, maxWidth, showChanges);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetEmailSettings
        /// </summary>
        [Test]
        public void GetEmailSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.GetEmailSettings(accountId, envelopeId);
            //Assert.IsInstanceOf<EmailSettings> (response, "response is EmailSettings");
        }
        
        /// <summary>
        /// Test GetEnvelope
        /// </summary>
        [Test]
        public void GetEnvelopeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string advancedUpdate = null;
            //string include = null;
            //var response = instance.GetEnvelope(accountId, envelopeId, advancedUpdate, include);
            //Assert.IsInstanceOf<Envelope> (response, "response is Envelope");
        }
        
        /// <summary>
        /// Test GetFormData
        /// </summary>
        [Test]
        public void GetFormDataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.GetFormData(accountId, envelopeId);
            //Assert.IsInstanceOf<EnvelopeFormData> (response, "response is EnvelopeFormData");
        }
        
        /// <summary>
        /// Test GetLock
        /// </summary>
        [Test]
        public void GetLockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.GetLock(accountId, envelopeId);
            //Assert.IsInstanceOf<LockInformation> (response, "response is LockInformation");
        }
        
        /// <summary>
        /// Test GetNotificationSettings
        /// </summary>
        [Test]
        public void GetNotificationSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.GetNotificationSettings(accountId, envelopeId);
            //Assert.IsInstanceOf<Notification> (response, "response is Notification");
        }
        
        /// <summary>
        /// Test GetRecipientDocumentVisibility
        /// </summary>
        [Test]
        public void GetRecipientDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //var response = instance.GetRecipientDocumentVisibility(accountId, envelopeId, recipientId);
            //Assert.IsInstanceOf<DocumentVisibilityList> (response, "response is DocumentVisibilityList");
        }
        
        /// <summary>
        /// Test GetRecipientInitialsImage
        /// </summary>
        [Test]
        public void GetRecipientInitialsImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //string includeChrome = null;
            //var response = instance.GetRecipientInitialsImage(accountId, envelopeId, recipientId, includeChrome);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetRecipientSignature
        /// </summary>
        [Test]
        public void GetRecipientSignatureTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //var response = instance.GetRecipientSignature(accountId, envelopeId, recipientId);
            //Assert.IsInstanceOf<UserSignature> (response, "response is UserSignature");
        }
        
        /// <summary>
        /// Test GetRecipientSignatureImage
        /// </summary>
        [Test]
        public void GetRecipientSignatureImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //string includeChrome = null;
            //var response = instance.GetRecipientSignatureImage(accountId, envelopeId, recipientId, includeChrome);
            //Assert.IsInstanceOf<System.IO.Stream> (response, "response is System.IO.Stream");
        }
        
        /// <summary>
        /// Test GetTemplateRecipientDocumentVisibility
        /// </summary>
        [Test]
        public void GetTemplateRecipientDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string recipientId = null;
            //string templateId = null;
            //var response = instance.GetTemplateRecipientDocumentVisibility(accountId, recipientId, templateId);
            //Assert.IsInstanceOf<DocumentVisibilityList> (response, "response is DocumentVisibilityList");
        }
        
        /// <summary>
        /// Test ListAuditEvents
        /// </summary>
        [Test]
        public void ListAuditEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.ListAuditEvents(accountId, envelopeId);
            //Assert.IsInstanceOf<EnvelopeAuditEventResponse> (response, "response is EnvelopeAuditEventResponse");
        }
        
        /// <summary>
        /// Test ListCustomFields
        /// </summary>
        [Test]
        public void ListCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.ListCustomFields(accountId, envelopeId);
            //Assert.IsInstanceOf<CustomFieldsEnvelope> (response, "response is CustomFieldsEnvelope");
        }
        
        /// <summary>
        /// Test ListDocumentFields
        /// </summary>
        [Test]
        public void ListDocumentFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //var response = instance.ListDocumentFields(accountId, documentId, envelopeId);
            //Assert.IsInstanceOf<DocumentFieldsInformation> (response, "response is DocumentFieldsInformation");
        }
        
        /// <summary>
        /// Test ListDocuments
        /// </summary>
        [Test]
        public void ListDocumentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string includeMetadata = null;
            //var response = instance.ListDocuments(accountId, envelopeId, includeMetadata);
            //Assert.IsInstanceOf<EnvelopeDocumentsResult> (response, "response is EnvelopeDocumentsResult");
        }
        
        /// <summary>
        /// Test ListRecipients
        /// </summary>
        [Test]
        public void ListRecipientsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string includeAnchorTabLocations = null;
            //string includeExtended = null;
            //string includeMetadata = null;
            //string includeTabs = null;
            //var response = instance.ListRecipients(accountId, envelopeId, includeAnchorTabLocations, includeExtended, includeMetadata, includeTabs);
            //Assert.IsInstanceOf<Recipients> (response, "response is Recipients");
        }
        
        /// <summary>
        /// Test ListStatus
        /// </summary>
        [Test]
        public void ListStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string email = null;
            //string fromDate = null;
            //string startPosition = null;
            //string toDate = null;
            //EnvelopeIdsRequest envelopeIdsRequest = null;
            //var response = instance.ListStatus(accountId, email, fromDate, startPosition, toDate, envelopeIdsRequest);
            //Assert.IsInstanceOf<EnvelopesInformation> (response, "response is EnvelopesInformation");
        }
        
        /// <summary>
        /// Test ListStatusChanges
        /// </summary>
        [Test]
        public void ListStatusChangesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string acStatus = null;
            //string block = null;
            //string count = null;
            //string customField = null;
            //string email = null;
            //string envelopeIds = null;
            //string exclude = null;
            //string folderIds = null;
            //string folderTypes = null;
            //string fromDate = null;
            //string fromToStatus = null;
            //string include = null;
            //string intersectingFolderIds = null;
            //string order = null;
            //string orderBy = null;
            //string powerformids = null;
            //string searchText = null;
            //string startPosition = null;
            //string status = null;
            //string toDate = null;
            //string transactionIds = null;
            //string userFilter = null;
            //string userId = null;
            //string userName = null;
            //var response = instance.ListStatusChanges(accountId, acStatus, block, count, customField, email, envelopeIds, exclude, folderIds, folderTypes, fromDate, fromToStatus, include, intersectingFolderIds, order, orderBy, powerformids, searchText, startPosition, status, toDate, transactionIds, userFilter, userId, userName);
            //Assert.IsInstanceOf<EnvelopesInformation> (response, "response is EnvelopesInformation");
        }
        
        /// <summary>
        /// Test ListTabs
        /// </summary>
        [Test]
        public void ListTabsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //string includeAnchorTabLocations = null;
            //string includeMetadata = null;
            //var response = instance.ListTabs(accountId, envelopeId, recipientId, includeAnchorTabLocations, includeMetadata);
            //Assert.IsInstanceOf<Tabs> (response, "response is Tabs");
        }
        
        /// <summary>
        /// Test ListTemplates
        /// </summary>
        [Test]
        public void ListTemplatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string include = null;
            //var response = instance.ListTemplates(accountId, envelopeId, include);
            //Assert.IsInstanceOf<TemplateInformation> (response, "response is TemplateInformation");
        }
        
        /// <summary>
        /// Test ListTemplatesForDocument
        /// </summary>
        [Test]
        public void ListTemplatesForDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //string include = null;
            //var response = instance.ListTemplatesForDocument(accountId, documentId, envelopeId, include);
            //Assert.IsInstanceOf<TemplateInformation> (response, "response is TemplateInformation");
        }
        
        /// <summary>
        /// Test PutAttachment
        /// </summary>
        [Test]
        public void PutAttachmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string attachmentId = null;
            //string envelopeId = null;
            //Attachment attachment = null;
            //var response = instance.PutAttachment(accountId, attachmentId, envelopeId, attachment);
            //Assert.IsInstanceOf<EnvelopeAttachmentsResult> (response, "response is EnvelopeAttachmentsResult");
        }
        
        /// <summary>
        /// Test PutAttachments
        /// </summary>
        [Test]
        public void PutAttachmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeAttachmentsRequest envelopeAttachmentsRequest = null;
            //var response = instance.PutAttachments(accountId, envelopeId, envelopeAttachmentsRequest);
            //Assert.IsInstanceOf<EnvelopeAttachmentsResult> (response, "response is EnvelopeAttachmentsResult");
        }
        
        /// <summary>
        /// Test RotateDocumentPage
        /// </summary>
        [Test]
        public void RotateDocumentPageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //string pageNumber = null;
            //PageRequest pageRequest = null;
            //instance.RotateDocumentPage(accountId, documentId, envelopeId, pageNumber, pageRequest);
            
        }
        
        /// <summary>
        /// Test Update
        /// </summary>
        [Test]
        public void UpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string advancedUpdate = null;
            //string resendEnvelope = null;
            //Envelope envelope = null;
            //var response = instance.Update(accountId, envelopeId, advancedUpdate, resendEnvelope, envelope);
            //Assert.IsInstanceOf<EnvelopeUpdateSummary> (response, "response is EnvelopeUpdateSummary");
        }
        
        /// <summary>
        /// Test UpdateChunkedUpload
        /// </summary>
        [Test]
        public void UpdateChunkedUploadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string chunkedUploadId = null;
            //string action = null;
            //var response = instance.UpdateChunkedUpload(accountId, chunkedUploadId, action);
            //Assert.IsInstanceOf<ChunkedUploadResponse> (response, "response is ChunkedUploadResponse");
        }
        
        /// <summary>
        /// Test UpdateChunkedUploadPart
        /// </summary>
        [Test]
        public void UpdateChunkedUploadPartTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string chunkedUploadId = null;
            //string chunkedUploadPartSeq = null;
            //ChunkedUploadRequest chunkedUploadRequest = null;
            //var response = instance.UpdateChunkedUploadPart(accountId, chunkedUploadId, chunkedUploadPartSeq, chunkedUploadRequest);
            //Assert.IsInstanceOf<ChunkedUploadResponse> (response, "response is ChunkedUploadResponse");
        }
        
        /// <summary>
        /// Test UpdateCustomFields
        /// </summary>
        [Test]
        public void UpdateCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //CustomFields customFields = null;
            //var response = instance.UpdateCustomFields(accountId, envelopeId, customFields);
            //Assert.IsInstanceOf<CustomFields> (response, "response is CustomFields");
        }
        
        /// <summary>
        /// Test UpdateDocument
        /// </summary>
        [Test]
        public void UpdateDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //string applyDocumentFields = null;
            //instance.UpdateDocument(accountId, documentId, envelopeId, applyDocumentFields);
            
        }
        
        /// <summary>
        /// Test UpdateDocumentFields
        /// </summary>
        [Test]
        public void UpdateDocumentFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string documentId = null;
            //string envelopeId = null;
            //DocumentFieldsInformation documentFieldsInformation = null;
            //var response = instance.UpdateDocumentFields(accountId, documentId, envelopeId, documentFieldsInformation);
            //Assert.IsInstanceOf<DocumentFieldsInformation> (response, "response is DocumentFieldsInformation");
        }
        
        /// <summary>
        /// Test UpdateDocuments
        /// </summary>
        [Test]
        public void UpdateDocumentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string applyDocumentFields = null;
            //EnvelopeDefinition envelopeDefinition = null;
            //var response = instance.UpdateDocuments(accountId, envelopeId, applyDocumentFields, envelopeDefinition);
            //Assert.IsInstanceOf<EnvelopeDocumentsResult> (response, "response is EnvelopeDocumentsResult");
        }
        
        /// <summary>
        /// Test UpdateEmailSettings
        /// </summary>
        [Test]
        public void UpdateEmailSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EmailSettings emailSettings = null;
            //var response = instance.UpdateEmailSettings(accountId, envelopeId, emailSettings);
            //Assert.IsInstanceOf<EmailSettings> (response, "response is EmailSettings");
        }
        
        /// <summary>
        /// Test UpdateLock
        /// </summary>
        [Test]
        public void UpdateLockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //LockRequest lockRequest = null;
            //var response = instance.UpdateLock(accountId, envelopeId, lockRequest);
            //Assert.IsInstanceOf<LockInformation> (response, "response is LockInformation");
        }
        
        /// <summary>
        /// Test UpdateNotificationSettings
        /// </summary>
        [Test]
        public void UpdateNotificationSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeNotificationRequest envelopeNotificationRequest = null;
            //var response = instance.UpdateNotificationSettings(accountId, envelopeId, envelopeNotificationRequest);
            //Assert.IsInstanceOf<Notification> (response, "response is Notification");
        }
        
        /// <summary>
        /// Test UpdateRecipientDocumentVisibility
        /// </summary>
        [Test]
        public void UpdateRecipientDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //DocumentVisibilityList documentVisibilityList = null;
            //var response = instance.UpdateRecipientDocumentVisibility(accountId, envelopeId, recipientId, documentVisibilityList);
            //Assert.IsInstanceOf<DocumentVisibilityList> (response, "response is DocumentVisibilityList");
        }
        
        /// <summary>
        /// Test UpdateRecipientInitialsImage
        /// </summary>
        [Test]
        public void UpdateRecipientInitialsImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //instance.UpdateRecipientInitialsImage(accountId, envelopeId, recipientId);
            
        }
        
        /// <summary>
        /// Test UpdateRecipientSignatureImage
        /// </summary>
        [Test]
        public void UpdateRecipientSignatureImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //instance.UpdateRecipientSignatureImage(accountId, envelopeId, recipientId);
            
        }
        
        /// <summary>
        /// Test UpdateRecipients
        /// </summary>
        [Test]
        public void UpdateRecipientsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string resendEnvelope = null;
            //Recipients recipients = null;
            //var response = instance.UpdateRecipients(accountId, envelopeId, resendEnvelope, recipients);
            //Assert.IsInstanceOf<RecipientsUpdateSummary> (response, "response is RecipientsUpdateSummary");
        }
        
        /// <summary>
        /// Test UpdateRecipientsDocumentVisibility
        /// </summary>
        [Test]
        public void UpdateRecipientsDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //DocumentVisibilityList documentVisibilityList = null;
            //var response = instance.UpdateRecipientsDocumentVisibility(accountId, envelopeId, documentVisibilityList);
            //Assert.IsInstanceOf<DocumentVisibilityList> (response, "response is DocumentVisibilityList");
        }
        
        /// <summary>
        /// Test UpdateTabs
        /// </summary>
        [Test]
        public void UpdateTabsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //Tabs tabs = null;
            //var response = instance.UpdateTabs(accountId, envelopeId, recipientId, tabs);
            //Assert.IsInstanceOf<Tabs> (response, "response is Tabs");
        }
        
        /// <summary>
        /// Test UpdateTemplateRecipientDocumentVisibility
        /// </summary>
        [Test]
        public void UpdateTemplateRecipientDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string recipientId = null;
            //string templateId = null;
            //TemplateDocumentVisibilityList templateDocumentVisibilityList = null;
            //var response = instance.UpdateTemplateRecipientDocumentVisibility(accountId, recipientId, templateId, templateDocumentVisibilityList);
            //Assert.IsInstanceOf<TemplateDocumentVisibilityList> (response, "response is TemplateDocumentVisibilityList");
        }
        
        /// <summary>
        /// Test UpdateTemplateRecipientsDocumentVisibility
        /// </summary>
        [Test]
        public void UpdateTemplateRecipientsDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string templateId = null;
            //TemplateDocumentVisibilityList templateDocumentVisibilityList = null;
            //var response = instance.UpdateTemplateRecipientsDocumentVisibility(accountId, templateId, templateDocumentVisibilityList);
            //Assert.IsInstanceOf<TemplateDocumentVisibilityList> (response, "response is TemplateDocumentVisibilityList");
        }
        
    }

}
