/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing BillingPaymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingPaymentResponseTests
    {
        // TODO uncomment below to declare an instance variable for BillingPaymentResponse
        //private BillingPaymentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingPaymentResponse
            //instance = new BillingPaymentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingPaymentResponse
        /// </summary>
        [Test]
        public void BillingPaymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingPaymentResponse
            //Assert.IsInstanceOfType<BillingPaymentResponse> (instance, "variable 'instance' is a BillingPaymentResponse");
        }

        /// <summary>
        /// Test the property 'BillingPayments'
        /// </summary>
        [Test]
        public void BillingPaymentsTest()
        {
            // TODO unit test for the property 'BillingPayments'
        }

    }

}
