/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing EnvelopeFormData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnvelopeFormDataTests
    {
        // TODO uncomment below to declare an instance variable for EnvelopeFormData
        //private EnvelopeFormData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvelopeFormData
            //instance = new EnvelopeFormData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeFormData
        /// </summary>
        [Test]
        public void EnvelopeFormDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvelopeFormData
            //Assert.IsInstanceOfType<EnvelopeFormData> (instance, "variable 'instance' is a EnvelopeFormData");
        }

        /// <summary>
        /// Test the property 'EmailSubject'
        /// </summary>
        [Test]
        public void EmailSubjectTest()
        {
            // TODO unit test for the property 'EmailSubject'
        }
        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [Test]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'FormData'
        /// </summary>
        [Test]
        public void FormDataTest()
        {
            // TODO unit test for the property 'FormData'
        }
        /// <summary>
        /// Test the property 'RecipientFormData'
        /// </summary>
        [Test]
        public void RecipientFormDataTest()
        {
            // TODO unit test for the property 'RecipientFormData'
        }
        /// <summary>
        /// Test the property 'SentDateTime'
        /// </summary>
        [Test]
        public void SentDateTimeTest()
        {
            // TODO unit test for the property 'SentDateTime'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
