/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing EnvelopeSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnvelopeSummaryTests
    {
        // TODO uncomment below to declare an instance variable for EnvelopeSummary
        //private EnvelopeSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvelopeSummary
            //instance = new EnvelopeSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeSummary
        /// </summary>
        [Test]
        public void EnvelopeSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvelopeSummary
            //Assert.IsInstanceOfType<EnvelopeSummary> (instance, "variable 'instance' is a EnvelopeSummary");
        }

        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [Test]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusDateTime'
        /// </summary>
        [Test]
        public void StatusDateTimeTest()
        {
            // TODO unit test for the property 'StatusDateTime'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
