/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing LockRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LockRequestTests
    {
        // TODO uncomment below to declare an instance variable for LockRequest
        //private LockRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LockRequest
            //instance = new LockRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LockRequest
        /// </summary>
        [Test]
        public void LockRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LockRequest
            //Assert.IsInstanceOfType<LockRequest> (instance, "variable 'instance' is a LockRequest");
        }

        /// <summary>
        /// Test the property 'LockDurationInSeconds'
        /// </summary>
        [Test]
        public void LockDurationInSecondsTest()
        {
            // TODO unit test for the property 'LockDurationInSeconds'
        }
        /// <summary>
        /// Test the property 'LockedByApp'
        /// </summary>
        [Test]
        public void LockedByAppTest()
        {
            // TODO unit test for the property 'LockedByApp'
        }
        /// <summary>
        /// Test the property 'LockType'
        /// </summary>
        [Test]
        public void LockTypeTest()
        {
            // TODO unit test for the property 'LockType'
        }
        /// <summary>
        /// Test the property 'TemplatePassword'
        /// </summary>
        [Test]
        public void TemplatePasswordTest()
        {
            // TODO unit test for the property 'TemplatePassword'
        }
        /// <summary>
        /// Test the property 'UseScratchPad'
        /// </summary>
        [Test]
        public void UseScratchPadTest()
        {
            // TODO unit test for the property 'UseScratchPad'
        }

    }

}
