/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DocuSign.eSign.Api;
using DocuSign.eSign.Model;
using DocuSign.eSign.Client;
using System.Reflection;

namespace DocuSign.eSign.Test
{
    /// <summary>
    ///  Class for testing NotaryJournalCredibleWitness
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotaryJournalCredibleWitnessTests
    {
        // TODO uncomment below to declare an instance variable for NotaryJournalCredibleWitness
        //private NotaryJournalCredibleWitness instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotaryJournalCredibleWitness
            //instance = new NotaryJournalCredibleWitness();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotaryJournalCredibleWitness
        /// </summary>
        [Test]
        public void NotaryJournalCredibleWitnessInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NotaryJournalCredibleWitness
            //Assert.IsInstanceOfType<NotaryJournalCredibleWitness> (instance, "variable 'instance' is a NotaryJournalCredibleWitness");
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SignatureImage'
        /// </summary>
        [Test]
        public void SignatureImageTest()
        {
            // TODO unit test for the property 'SignatureImage'
        }

    }

}
